# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: ProjectArk
email: matin294@gmail.com
# description: >- # this means to ignore newlines until "baseurl:"
#   A world full of creation
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://ProjectArkClub.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ""
github_username:  ProjectArkClub
author: ProjectArkClub
owner_name: ProjectArkClub
owner_url: https://github.com/ProjectArkClub
cdn: 
# cdn: https://cdn.jsdelivr.us/gh/ProjectArkClub/ProjectArkClub.github.io
# cdn: https://purge.jsdelivr.net/gh/ProjectArkClub/ProjectArkClub.github.io
# cdn: https://jsd.cdn.zzko.cn/gh/ProjectArkClub/Resource
# cdn: https://cdn.jsdelivr.net/gh/ProjectArkClub/ProjectArkClub.github.io
# cdn: https://fastgit.projectark.vip/https://raw.githubusercontent.com/ProjectArkClub/ProjectArkClub.github.io/main/
fastgit_url: https://fastgit.projectark.vip/https://raw.githubusercontent.com/ProjectArkClub/Download/main/
bucket_url: https://download-projectark-1258640941.cos.ap-shanghai.myqcloud.com
google_analytics: G-Q0B9W70VGJ
projectArk: False
projectArk_version: v4.590
projectArk_version_update: 2023/3/15
projectArk_update_version: v3.7.9.0

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

